//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeApp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your recipe backup was successful..
        /// </summary>
        internal static string BackupSuccessful {
            get {
                return ResourceManager.GetString("BackupSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic data.
        /// </summary>
        internal static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        internal static string Directions {
            get {
                return ResourceManager.GetString("Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit recipe.
        /// </summary>
        internal static string EditRecipe {
            get {
                return ResourceManager.GetString("EditRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Ingredient_Name {
            get {
                return ResourceManager.GetString("Ingredient_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Ingredient_Quantity {
            get {
                return ResourceManager.GetString("Ingredient_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Ingredient_Unit {
            get {
                return ResourceManager.GetString("Ingredient_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup found..
        /// </summary>
        internal static string NoBackupFound {
            get {
                return ResourceManager.GetString("NoBackupFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photo was picked..
        /// </summary>
        internal static string NoPhotoPicked {
            get {
                return ResourceManager.GetString("NoPhotoPicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not currenty support the functionality to pick photos..
        /// </summary>
        internal static string PickPhotoNotSupported {
            get {
                return ResourceManager.GetString("PickPhotoNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When restoring, all exisiting recipes will be deleted. Do you want to continue anyway?.
        /// </summary>
        internal static string QuestionDeleteAndRestore {
            get {
                return ResourceManager.GetString("QuestionDeleteAndRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your changes?.
        /// </summary>
        internal static string QuestionSaveChanges {
            get {
                return ResourceManager.GetString("QuestionSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baking/Cooking time.
        /// </summary>
        internal static string Recipe_BakingCookingTime {
            get {
                return ResourceManager.GetString("Recipe_BakingCookingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Recipe_Name {
            get {
                return ResourceManager.GetString("Recipe_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall time.
        /// </summary>
        internal static string Recipe_OverallTime {
            get {
                return ResourceManager.GetString("Recipe_OverallTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation time.
        /// </summary>
        internal static string Recipe_PreparationTime {
            get {
                return ResourceManager.GetString("Recipe_PreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest time.
        /// </summary>
        internal static string Recipe_RestTime {
            get {
                return ResourceManager.GetString("Recipe_RestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving(s).
        /// </summary>
        internal static string Recipe_Servings {
            get {
                return ResourceManager.GetString("Recipe_Servings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe details.
        /// </summary>
        internal static string RecipeDetails {
            get {
                return ResourceManager.GetString("RecipeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your recipe restore was successful..
        /// </summary>
        internal static string RestoreSuccessful {
            get {
                return ResourceManager.GetString("RestoreSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search recipe(s).
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string Unit_Gram {
            get {
                return ResourceManager.GetString("Unit_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        internal static string Unit_Milliliter {
            get {
                return ResourceManager.GetString("Unit_Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack.
        /// </summary>
        internal static string Unit_Pack {
            get {
                return ResourceManager.GetString("Unit_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcs.
        /// </summary>
        internal static string Unit_Piece {
            get {
                return ResourceManager.GetString("Unit_Piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pinch(es).
        /// </summary>
        internal static string Unit_Pinch {
            get {
                return ResourceManager.GetString("Unit_Pinch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slice(s).
        /// </summary>
        internal static string Unit_Slice {
            get {
                return ResourceManager.GetString("Unit_Slice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbsp.
        /// </summary>
        internal static string Unit_Tablespoon {
            get {
                return ResourceManager.GetString("Unit_Tablespoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tspn.
        /// </summary>
        internal static string Unit_Teaspoon {
            get {
                return ResourceManager.GetString("Unit_Teaspoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Undefined {
            get {
                return ResourceManager.GetString("Unit_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
